Algoritmo "Enquanto_Conta1a10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/2/2024
Var
// Seção de Declarações das variáveis 
  c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   C <- 0
   
   Enquanto (C < 10) faça
   C <- C + 1
   Escreva(C)
   Fimenquanto

Fimalgoritmo