Algoritmo "Fibonacci2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/3/2024
Var

   C, T1, T2, T3: Inteiro

inicio

   T1 <- 0
   Escreva(T1)
   T2 <- 1
   Escreva(T2)

   Para C de 1 até 13 faça
      T3 <- T1 + T2
      Escreva (T3)
      T1 <- T2
      T2 <- T3
   Fimpara

Fimalgoritmo