Algoritmo "Fibonacci"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/3/2024
Var

    C1, N1, N2, N3: INTEIRO

inicio

    N1 <- 0
    N2 <- 1

    Para C1 <- 1 ate 15 faça

         Escreva (N3)

         N1 <- N2
         N2 <- N3
         N3 <- N1 + N2
    FimPara

Fimalgoritmo